"""Self-contained HTML report for ``courtgraph demo --report PATH``.

No external assets, no JavaScript: inline CSS and inline SVG only, so the file
opens anywhere and prints cleanly. Every section is labeled as synthetic
demonstration data.
"""

from __future__ import annotations

import html
from pathlib import Path
from typing import Any

from courtgraph import __version__
from courtgraph.chemistry.chemistry_model import ChemistryModel
from courtgraph.chemistry.evaluate import EvaluationSummary, HoldoutResult
from courtgraph.chemistry.synthetic import GroundTruth

_CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body { margin: 0; font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI",
  Roboto, Helvetica, Arial, sans-serif; color: #1a1a1a; background: #fbfbfa; }
main { max-width: 940px; margin: 0 auto; padding: 32px 24px 80px; }
h1 { font-size: 1.7rem; margin: 0 0 4px; }
h2 { font-size: 1.15rem; margin: 40px 0 12px; border-bottom: 2px solid #e4e4e2;
  padding-bottom: 6px; }
h3 { font-size: 1rem; margin: 22px 0 8px; }
p { margin: 8px 0; }
small, .muted { color: #6b6b68; }
.banner { background: #4b3b00; color: #ffe9a8; border-radius: 8px; padding: 12px 16px;
  font-weight: 600; margin: 14px 0 8px; }
table { border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 0.92rem; }
th, td { text-align: right; padding: 6px 9px; border-bottom: 1px solid #e4e4e2; }
th:first-child, td:first-child { text-align: left; }
thead th { border-bottom: 2px solid #cfcfcc; white-space: nowrap; }
tbody tr:hover { background: #f2f2ef; }
.good { color: #14670e; font-weight: 600; }
.bad { color: #9a1616; font-weight: 600; }
.pill { display: inline-block; padding: 1px 8px; border-radius: 999px;
  font-size: 0.8rem; background: #e7e7e4; }
.pill.unseen { background: #f6d9d0; }
.pill.partial { background: #f6ecc9; }
.pill.seen { background: #d7ecd5; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(210px, 1fr));
  gap: 12px; margin: 12px 0; }
.card { background: #fff; border: 1px solid #e4e4e2; border-radius: 8px;
  padding: 12px 14px; }
.card .n { font-size: 1.35rem; font-weight: 700; }
figure { margin: 12px 0; }
figcaption { font-size: 0.85rem; color: #6b6b68; margin-top: 4px; }
code { background: #eee; padding: 1px 5px; border-radius: 4px; font-size: 0.88em; }
@media (prefers-color-scheme: dark) {
  body { color: #e9e9e6; background: #17171a; }
  h2 { border-color: #333; } th, td { border-color: #333; }
  thead th { border-color: #444; } tbody tr:hover { background: #202024; }
  .card { background: #1e1e22; border-color: #333; }
  .pill { background: #333; } code { background: #333; }
  .banner { background: #6b5200; color: #fff2cf; }
  .good { color: #7fd67a; } .bad { color: #e88; }
}
"""


def write_report(
    path: Path,
    *,
    summary: EvaluationSummary,
    model: ChemistryModel,
    truth: GroundTruth | None,
    examples: tuple[dict[str, Any], ...],
    seed: int,
) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(
        [
            _header(summary, seed),
            _dataset_section(summary),
            _metrics_section(summary),
            _decomposition_section(examples),
            _recovery_section(summary, truth),
            _uncertainty_section(summary),
            _methodology_section(model, summary),
        ]
    )
    doc = (
        "<!doctype html>\n<html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<title>CourtGraph chemistry MVP - synthetic demo</title>"
        f"<style>{_CSS}</style></head><body><main>{body}</main></body></html>\n"
    )
    path.write_text(doc, encoding="utf-8")
    return path


def _e(value: Any) -> str:
    return html.escape(str(value))


def _fmt(value: float | None, digits: int = 2) -> str:
    if value is None:
        return "&mdash;"
    return f"{value:.{digits}f}"


def _pct(value: float) -> str:
    cls = "good" if value > 0.5 else ("bad" if value < -0.5 else "muted")
    return f"<span class='{cls}'>{value:+.0f}%</span>"


def _header(summary: EvaluationSummary, seed: int) -> str:
    return (
        "<h1>CourtGraph &mdash; lineup chemistry MVP</h1>"
        "<p class='muted'>One end-to-end vertical slice: synthetic stints &rarr; "
        "leakage-safe splits &rarr; additive ridge baseline &rarr; "
        "permutation-invariant low-rank embedding model &rarr; decomposition, "
        "evaluation, and uncertainty.</p>"
        "<div class='banner'>SYNTHETIC DEMONSTRATION DATA &mdash; generated by a "
        "known model. These numbers describe the machinery, not the NBA.</div>"
        f"<p class='muted'>seed {seed} &middot; courtgraph {_e(__version__)} &middot; "
        "deterministic</p>"
    )


def _dataset_section(summary: EvaluationSummary) -> str:
    d = summary.dataset
    cards = "".join(
        f"<div class='card'><div class='n'>{_e(v)}</div><small>{_e(k)}</small></div>"
        for k, v in [
            ("stints", d["stints"]),
            ("possessions", d["possessions"]),
            ("players", d["players"]),
            ("seasons", len(d["seasons"])),
        ]
    )
    return f"<h2>1. Synthetic dataset</h2><div class='grid'>{cards}</div>"


def _metrics_section(summary: EvaluationSummary) -> str:
    rows = []
    for h in summary.holdouts:
        m = h.metrics
        macro_add = m.get(
            "additive_rmse_truth_macro", m.get("additive_rmse_realized_macro")
        )
        macro_full = m.get("full_rmse_truth_macro", m.get("full_rmse_realized_macro"))
        ci = h.approximate_delta_interval
        rows.append(
            "<tr>"
            f"<td>{_e(h.kind)}</td>"
            f"<td>{h.n_test_groups}</td>"
            f"<td>{_fmt(m.get('additive_rmse_realized_micro'))}</td>"
            f"<td>{_fmt(m.get('full_rmse_realized_micro'))}</td>"
            f"<td>{_fmt(macro_add)}</td>"
            f"<td>{_fmt(macro_full)}</td>"
            f"<td>{_pct(h.headline_improvement_pct)}</td>"
            f"<td>{_fmt(ci.get('point'))} "
            f"[{_fmt(ci.get('lower80'))}, {_fmt(ci.get('upper80'))}]</td>"
            f"<td>{len(h.leakage_violations)}</td>"
            "</tr>"
        )
    truth_note = (
        "Macro RMSE is against the <b>known generative truth</b> (model-recovery "
        "view); "
        if any(m.metrics.get("headline_metric_is_truth") for m in summary.holdouts)
        else ""
    )
    return (
        "<h2>2. Additive baseline vs full model</h2>"
        "<p class='muted'>Points per 100 possessions. Micro = possession-weighted "
        "stint level; macro = equal-weight per held-out group. "
        f"{truth_note}the &Delta; column is an approximate game-block-bootstrap "
        "interval on RMSE(additive) &minus; RMSE(full).</p>"
        "<table><thead><tr>"
        "<th>holdout</th><th>test groups</th>"
        "<th>add micro</th><th>full micro</th>"
        "<th>add macro</th><th>full macro</th><th>improvement</th>"
        "<th>&Delta; RMSE (approx 80%)</th><th>leakage</th>"
        "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>"
        "<p class='muted'>The realized-outcome micro metric is dominated by "
        "possession noise, so a small chemistry signal barely moves it &mdash; "
        "this is expected (research contract &sect;14). The signal shows in the "
        "macro / truth-referenced view and in section 4.</p>"
    )


def _bar_svg(parts: list[tuple[str, float]], width: int = 420) -> str:
    values = [v for _, v in parts]
    span = max(1e-6, max(abs(min(values)), abs(max(values))))
    mid = width / 2
    scale = (width / 2 - 60) / span
    rows = []
    h = 26
    for i, (label, value) in enumerate(parts):
        y = i * (h + 6)
        x = mid if value >= 0 else mid + value * scale
        w = abs(value) * scale
        color = "#3b7dd8" if value >= 0 else "#d8663b"
        rows.append(
            f"<rect x='{x:.1f}' y='{y}' width='{w:.1f}' height='{h}' fill='{color}' />"
            f"<text x='6' y='{y + h - 8}' font-size='12'>{_e(label)}</text>"
            f"<text x='{width - 4}' y='{y + h - 8}' font-size='12' "
            f"text-anchor='end'>{value:+.1f}</text>"
        )
    height = len(parts) * (h + 6)
    return (
        f"<svg viewBox='0 0 {width} {height}' width='100%' "
        f"style='max-width:{width}px'>"
        f"<line x1='{mid}' y1='0' x2='{mid}' y2='{height}' stroke='#999' />"
        + "".join(rows)
        + "</svg>"
    )


def _decomposition_section(examples: tuple[dict[str, Any], ...]) -> str:
    if not examples:
        return ""
    blocks = []
    for ex in examples[:4]:
        d = ex["decomposition"]
        parts = [
            ("talent (T)", d["talent"]),
            ("interaction (C)", d["interaction"]),
            ("context (K)", d["context"]),
            ("total V", d["total"]),
        ]
        truth_line = ""
        if "truth" in ex:
            t = ex["truth"]
            truth_line = (
                "<figcaption>true split &mdash; T "
                f"{t['talent']:.1f}, C {t['interaction']:+.1f}, "
                f"K {t['context']:+.1f}, V {t['total']:.1f}</figcaption>"
            )
        blocks.append(
            "<figure>"
            f"<h3>Unseen offense {_e(ex['offense'])}</h3>"
            f"{_bar_svg(parts)}"
            f"<figcaption>predicted C 80% band "
            f"[{d['interaction_lower']:+.1f}, {d['interaction_upper']:+.1f}], "
            f"P(C&gt;0) = {d['prob_interaction_positive']:.2f}, "
            f"novelty <span class='pill'>{_e(d['offense_novelty'])}</span>"
            f"</figcaption>{truth_line}"
            "</figure>"
        )
    return (
        "<h2>3. Lineup-value decomposition (unseen lineups)</h2>"
        "<p class='muted'>Every predicted lineup value splits into individual "
        "talent, interaction surplus (the chemistry signal), and non-player "
        "context. Chemistry is the surplus, not the level.</p>" + "".join(blocks)
    )


def _scatter_svg(
    pairs: list[tuple[float, float]], xlabel: str, ylabel: str, size: int = 260
) -> str:
    if not pairs:
        return ""
    xs = [x for x, _ in pairs]
    ys = [y for _, y in pairs]
    xspan = max(1e-6, max(xs) - min(xs))
    yspan = max(1e-6, max(ys) - min(ys))
    pad = 34

    def px(x: float) -> float:
        return pad + (x - min(xs)) / xspan * (size - 2 * pad)

    def py(y: float) -> float:
        return size - pad - (y - min(ys)) / yspan * (size - 2 * pad)

    dots = "".join(
        f"<circle cx='{px(x):.1f}' cy='{py(y):.1f}' r='2.5' fill='#3b7dd8' "
        f"fill-opacity='0.55' />"
        for x, y in pairs
    )
    return (
        f"<svg viewBox='0 0 {size} {size}' width='100%' style='max-width:{size}px'>"
        f"<rect x='{pad}' y='{pad}' width='{size - 2 * pad}' height='{size - 2 * pad}' "
        "fill='none' stroke='#ccc' />"
        f"{dots}"
        f"<text x='{size / 2}' y='{size - 6}' font-size='11' text-anchor='middle'>"
        f"{_e(xlabel)}</text>"
        f"<text x='12' y='{size / 2}' font-size='11' text-anchor='middle' "
        f"transform='rotate(-90 12 {size / 2})'>{_e(ylabel)}</text>"
        "</svg>"
    )


def _recovery_section(summary: EvaluationSummary, truth: GroundTruth | None) -> str:
    if not summary.recovery:
        return ""
    r = summary.recovery
    rows = "".join(
        f"<tr><td>{_e(k.replace('_', ' '))}</td><td>{_fmt(v, 3)}</td></tr>"
        for k, v in r.items()
    )
    return (
        "<h2>4. Recovery of the known generative structure</h2>"
        "<p class='muted'>Correlation between the model's estimates and the latent "
        "parameters the generator actually used. The additive ridge should recover "
        "individual talent; the low-rank pathway should recover the interaction "
        "structure the additive model cannot see.</p>"
        f"<table><thead><tr><th>quantity</th><th>corr(model, truth)</th></tr>"
        f"</thead><tbody>{rows}</tbody></table>"
    )


def _uncertainty_section(summary: EvaluationSummary) -> str:
    rows = []
    for h in summary.holdouts:
        if h.kind == "chronological":
            continue
        for g in sorted(h.groups, key=lambda x: -x.test_possessions)[:8]:
            novelty_cls = {
                "seen": "seen",
                "partially-seen": "partial",
                "unseen": "unseen",
            }.get(g.novelty, "")
            rows.append(
                "<tr>"
                f"<td>{_e(h.kind)}: {_e(g.group_id)}</td>"
                f"<td><span class='pill {novelty_cls}'>{_e(g.novelty)}</span></td>"
                f"<td>{g.test_possessions}</td>"
                f"<td>{_fmt(g.realized_value, 1)}</td>"
                f"<td>{_fmt(g.additive_prediction, 1)}</td>"
                f"<td>{_fmt(g.full_prediction, 1)}</td>"
                f"<td>{_fmt(g.truth_value, 1)}</td>"
                f"<td>{g.interaction_mean:+.1f} &plusmn; {g.interaction_sd:.1f}</td>"
                f"<td>{g.prob_interaction_positive:.2f}</td>"
                "</tr>"
            )
    return (
        "<h2>5. Support, uncertainty, and example predictions</h2>"
        "<p class='muted'>Approximate interaction interval and P(C&gt;0) from a "
        "block-bootstrap ensemble (games resampled, additive path fixed). Every "
        "row carries its exposure and a novelty class.</p>"
        "<table><thead><tr>"
        "<th>held-out group</th><th>novelty</th><th>test poss</th>"
        "<th>realized</th><th>additive</th><th>full</th><th>truth</th>"
        "<th>C mean &plusmn; sd</th><th>P(C&gt;0)</th>"
        "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>"
    )


def _methodology_section(model: ChemistryModel, summary: EvaluationSummary) -> str:
    notes = "".join(f"<li>{_e(n)}</li>" for n in summary.notes)
    cfg = model.config
    return (
        "<h2>6. Method &amp; caveats</h2>"
        "<ul>"
        f"<li>Outcome: offensive points per 100 possessions, exposure-weighted.</li>"
        f"<li>Baseline: additive ridge RAPM, separate offense/defense talent, "
        f"ridge strength chosen by game-blocked CV.</li>"
        f"<li>Full model: additive skip path + rank-{cfg.rank} provision/need "
        "embeddings; interaction = sum over the offensive set (permutation "
        "invariant), trained on the cross-fitted additive residual, "
        "L2-regularized toward zero, zero-sum centered.</li>"
        f"<li>Interaction L2 selected: {model.interaction.l2:g} "
        f"(bootstrap ensemble size {len(model.interaction_ensemble)}).</li>"
        f"{notes}"
        "<li>Not built: live data ingestion, web serving, calibrated Bayesian "
        "uncertainty, model ladder rungs beyond low-rank embeddings.</li>"
        "</ul>"
        "<p class='muted'>Interfaces (versioned stint format, model artifact, "
        "splits) are shaped so real NBA stints replace the synthetic ones without "
        "code changes to the models or evaluation.</p>"
    )


__all__ = ["write_report", "HoldoutResult"]
